export const StrengthResponses = [
  "Shows strong leadership potential.",
  "Learns new concepts quickly.",
  "Demonstrates excellent problem-solving skills.",
  "Communicates ideas clearly.",
  "Consistently shows self-motivation.",
  "Pays attention to detail.",
  "Displays creativity in tasks.",
  "Works effectively in teams.",
  "Adapts well to new situations.",
  "Maintains a positive attitude.",
  "Has strong logical reasoning.",
  "Shows initiative in projects.",
  "Is reliable and consistent.",
  "Demonstrates strong time management.",
  "Has a growth-oriented mindset.",
  "Handles pressure effectively.",
  "Shows accountability for actions.",
  "Has good analytical thinking.",
  "Possesses strong work ethics.",
  "Demonstrates curiosity for learning.",
  "Exhibits strong organizational skills.",
  "Is disciplined in completing tasks.",
  "Stays focused despite distractions.",
  "Has clear long-term goals.",
  "Shows empathy toward peers.",
  "Expresses ideas confidently.",
  "Displays strong memory retention.",
  "Handles complex tasks efficiently.",
  "Keeps improving through feedback.",
  "Shows persistence in difficulties.",
  "Welcomes challenges enthusiastically.",
  "Balances academics and activities well.",
  "Solves conflicts peacefully.",
  "Learns from mistakes quickly.",
  "Focuses on personal improvement.",
  "Builds rapport easily with others.",
  "Presents work with clarity and structure.",
  "Performs well under deadlines.",
  "Shows discipline in self-study.",
  "Thinks strategically in tasks."
];

export const WeaknessResponses = [
  "Struggles with time management.",
  "Gets easily distracted.",
  "Procrastinates important tasks.",
  "Lacks consistency in daily work.",
  "Feels low confidence in new challenges.",
  "Avoids asking questions in class.",
  "Depends too much on external guidance.",
  "Has difficulty prioritizing tasks.",
  "Finds it hard to manage stress.",
  "Overthinks before taking action.",
  "Tends to rush through assignments.",
  "Lacks attention to detail.",
  "Gives up quickly when stuck.",
  "Avoids group participation.",
  "Struggles to maintain discipline.",
  "Shows irregular study patterns.",
  "Has trouble expressing ideas clearly.",
  "Often forgets important deadlines.",
  "Feels hesitation in decision-making.",
  "Lacks clarity in long-term planning.",
  "Has difficulty balancing tasks.",
  "Relies too much on last-minute efforts.",
  "Tends to doubt own abilities.",
  "Needs improvement in communication.",
  "Works slower under pressure.",
  "Loses focus during long tasks.",
  "Feels nervous during assessments.",
  "Avoids leadership responsibility.",
  "Lacks initiative in projects.",
  "Shows inconsistency in performance.",
  "Finds multitasking challenging.",
  "Takes criticism personally.",
  "Struggles with organizing materials.",
  "Forgets to review past learning.",
  "Has difficulty staying motivated.",
  "Needs improvement in collaboration.",
  "Reluctant to try new strategies.",
  "Sometimes mismanages energy throughout the day.",
  "Gets overwhelmed with workload.",
  "Needs better follow-through on tasks."
];

export const OpportunityResponses = [
  "Can explore advanced courses suited to interest.",
  "Has potential to join student leadership roles.",
  "Can participate in national-level competitions.",
  "Can develop skills through online certifications.",
  "Shows potential for extracurricular achievement.",
  "Could benefit from mentorship programs.",
  "Has scope to build strong portfolios early.",
  "Can join academic clubs for skill growth.",
  "Opportunity to enhance communication skills.",
  "Can take internships or volunteer roles.",
  "Has scope to improve digital literacy.",
  "Can explore creative skill development.",
  "Opportunity to build strong peer networks.",
  "Can take part in collaborative workshops.",
  "Potential to excel in project-based learning.",
  "Can explore entrepreneurship programs.",
  "Opportunity for specialization in interests.",
  "Can join hackathons or innovation events.",
  "Can participate in personality development sessions.",
  "Opportunity to improve leadership presence.",
  "Can strengthen discipline via productivity tools.",
  "Has chance to explore scholarship programs.",
  "Can attend seminars and expert talks.",
  "Opportunity to join language improvement programs.",
  "Can engage in research-based learning.",
  "Opportunity for future internships.",
  "Chance to expand technical skill set.",
  "Can work with peers on collaborative projects.",
  "Has access to digital learning platforms.",
  "Can try competitive examination prep early.",
  "Has opportunity to improve decision-making.",
  "Can join clubs to broaden thinking.",
  "Opportunity to practice presentation skills.",
  "Can explore global student communities.",
  "Potential to collaborate on innovation projects.",
  "Can strengthen creativity through workshops.",
  "Opportunity to receive teacher mentoring.",
  "Can build personal brand on digital platforms.",
  "Chance to develop teamwork effectiveness.",
  "Opportunity to join real-world learning activities."
];

export const ThreatResponses = [
  "Risk of distraction due to excessive screen time.",
  "High competition in chosen career path.",
  "Risk of losing interest due to academic pressure.",
  "Social media impacting study consistency.",
  "Peers influencing unproductive habits.",
  "Increasing difficulty in syllabus structure.",
  "Poor time management affecting results.",
  "Procrastination reducing academic output.",
  "Unhealthy lifestyle affecting performance.",
  "Fear of failure causing stress.",
  "Overdependence on technology.",
  "Lack of discipline harming long-term growth.",
  "Unstable routine reducing productivity.",
  "Negative peer comparison affecting confidence.",
  "Inconsistent study habits.",
  "Risk of burnout due to overload.",
  "Missing deadlines leading to backlog.",
  "Irregular sleep patterns affecting focus.",
  "Lack of parental/mentor support.",
  "Pressure of upcoming exams.",
  "Fear of public speaking causing hesitation.",
  "Low motivation reducing progress.",
  "Uncertainty about career direction.",
  "Inconsistent performance shaping self-doubt.",
  "Risk of falling behind due to procrastination.",
  "Distractions from entertainment platforms.",
  "External stress impacting academic mindset.",
  "Poor organization causing confusion.",
  "Emotional stress affecting concentration.",
  "Gaps in fundamentals affecting growth.",
  "Frequent breaks disrupting flow.",
  "Competitive environment causing anxiety.",
  "Lack of revision reducing retention.",
  "Weak planning impacting preparation.",
  "Fear of judgment while participating.",
  "Health issues reducing energy.",
  "Unproductive habits affecting consistency.",
  "Overthinking slowing decision-making.",
  "Peer pressure causing wrong priorities.",
  "Lack of confidence in starting new things."
];
