export const ThreatResponses = [
  "External distractions may reduce your study efficiency.",
  "Inconsistent routines may affect your academic growth.",
  "Peer pressure may cause unnecessary stress.",
  "High competition can impact your confidence at times.",
  "Overuse of social media may reduce your productivity.",
  "Negative comparisons with others may affect motivation.",
  "Irregular sleeping patterns may impact concentration.",
  "Stress from expectations may slow down your progress.",
  "Frequent distractions can hinder your long-term goals.",
  "Lack of a quiet study environment may reduce focus.",
  "Procrastination can lead to academic pressure.",
  "Unclear goals may cause confusion in your study direction.",
  "Too many tasks at once may cause burnout.",
  "Low confidence under pressure may limit performance.",
  "Fear of failure may stop you from trying new things.",
  "Health issues can interrupt consistent study routines.",
  "Emotional stress can affect your learning capacity.",
  "Negative peer influence may impact discipline.",
  "Unmanaged time can cause last-minute panic.",
  "Excess gaming or entertainment may distract from goals.",
  "Sudden schedule changes may disturb planning.",
  "Lack of guidance can slow personal growth.",
  "Unhealthy competition may affect self-esteem.",
  "Unstable motivation patterns may delay progress.",
  "Irregular practice may reduce skill development.",
  "Overthinking outcomes may block decision-making.",
  "Sudden academic pressure may affect performance.",
  "Too much multitasking may reduce accuracy.",
  "Fear of judgement may stop you from participating.",
  "Uncontrolled stress may reduce productivity."
];

export const OpportunityResponses = [
  "You have strong potential to expand your skills through new learning platforms.",
  "You can grow faster by engaging in more extracurricular activities.",
  "You have opportunities to develop leadership through group projects.",
  "You can improve significantly by taking online courses regularly.",
  "You can benefit from exploring new technologies and tools.",
  "You have a chance to strengthen academic performance through structured planning.",
  "You can grow by participating in workshops or competitions.",
  "You can explore new career paths that fit your interests.",
  "You have scope to collaborate with peers to enhance learning.",
  "You can develop creativity by working on personal projects.",
  "You can grow communication skills through public speaking activities.",
  "You can improve by seeking mentorship from teachers or seniors.",
  "You have opportunities to join clubs aligned with your skills.",
  "You can use digital resources to learn advanced concepts.",
  "You can enhance problem-solving abilities by practicing regularly.",
  "You have potential to shine in competitive exams with more practice.",
  "You can gain exposure by attending webinars and seminars.",
  "You can strengthen confidence through participation in events.",
  "You can build a strong portfolio by documenting your projects.",
  "You can explore internships or volunteering to gain experience.",
  "You can grow academically by utilizing library and e-learning materials.",
  "You can improve teamwork abilities through collaborative tasks.",
  "You have the opportunity to develop discipline with daily study habits.",
  "You can learn time-management by using planners or productivity apps.",
  "You can grow your creativity through design or art activities.",
  "You can enhance your adaptability by joining diverse groups.",
  "You have potential to excel by setting clear learning goals.",
  "You can boost confidence by challenging yourself with new experiences.",
  "You can gain new perspectives by interacting with knowledgeable people.",
  "You can strengthen your skills by consistently practicing daily."
];

export const WeaknessResponses = [
  "You sometimes struggle to maintain consistent focus.",
  "You may avoid difficult tasks due to self-doubt.",
  "You tend to delay assignments until the last moment.",
  "You get distracted easily while studying.",
  "You need to improve your time-management habits.",
  "You sometimes lack confidence in expressing your thoughts.",
  "You often feel overwhelmed when handling multiple tasks.",
  "You may depend too much on guidance instead of taking initiative.",
  "You face difficulty staying consistent with routines.",
  "You may hesitate to participate in group discussions.",
  "You sometimes underestimate your abilities.",
  "You can improve in setting clear academic goals.",
  "You occasionally struggle with planning before starting work.",
  "You may lose motivation when tasks become challenging.",
  "You tend to miss details due to rushing through work.",
  "You may feel pressure easily during competition.",
  "You sometimes avoid asking for help when needed.",
  "You have difficulty balancing study and personal time.",
  "You occasionally doubt your decisions.",
  "You may procrastinate tasks that seem complex.",
  "You sometimes struggle with maintaining discipline.",
  "You find it challenging to remain calm under stress.",
  "You may rely too much on external reminders.",
  "You sometimes struggle to retain new information quickly.",
  "You have difficulty managing distractions effectively.",
  "You may feel anxious before exams or evaluations.",
  "You sometimes lack direction in long-term planning.",
  "You tend to overthink small mistakes.",
  "You may avoid leadership roles due to hesitation.",
  "You sometimes lose interest when topics are lengthy."
];

export const StrengthResponses = [
  "You show strong confidence when facing new challenges.",
  "You approach difficult tasks with a positive and focused mindset.",
  "You demonstrate excellent consistency in completing your work.",
  "You are highly reliable and follow through on your commitments.",
  "You learn new concepts quickly and effectively.",
  "You maintain strong discipline in your academic routine.",
  "You display a natural sense of responsibility in your tasks.",
  "You communicate clearly and confidently with others.",
  "You have strong problem-solving abilities.",
  "You show great adaptability in changing situations.",
  "You stay motivated even when tasks become difficult.",
  "You actively seek opportunities to grow your skills.",
  "You collaborate well in group activities.",
  "You are creative and come up with unique ideas.",
  "You manage your time efficiently and stay organized.",
  "You remain calm and composed under pressure.",
  "You have strong leadership qualities.",
  "You pay attention to detail and maintain accuracy.",
  "You show curiosity and willingness to explore new knowledge.",
  "You are self-driven and take initiative without reminders.",
  "You maintain a positive attitude toward learning.",
  "You understand concepts deeply and logically.",
  "You remain consistent in your efforts across subjects.",
  "You set clear goals and work steadily toward them.",
  "You show discipline in managing distractions.",
  "You adapt well to different learning environments.",
  "You demonstrate maturity in decision-making.",
  "You stay focused for long periods when needed.",
  "You are good at breaking big tasks into smaller steps.",
  "You show excellent perseverance even during challenges."
];

